apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: monitoring-client
  namespace: default
spec:
  port:
    targetPort: 3000
  to:
    kind: Service
    name: prometheus-community-grafana 
    weight: 100
  wildcardPolicy: None
