apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-sample
spec:
  instances: 3
  imageName: 'quay.io/enterprisedb/postgresql:14.2'
  #imagePullPolicy: Never
  primaryUpdateStrategy: supervised

  # Reduce the frequency of standby HA slots updates to once every 5 minutes
  replicationSlots:
    highAvailability:
      enabled: true
    #updateInterval: 300

  minSyncReplicas: 1
  maxSyncReplicas: 1

  postgresql:
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all

  storage:
    size: 1Gi

  walStorage:
    resizeInUseVolumes: true
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"

  backup:
    barmanObjectStore:
      destinationPath: s3://database-backups/
      endpointURL: http://minio-client-minio-tenant.apps-crc.testing
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: backup-secret
        inheritFromIAMRole: false
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: backup-secret
    target: prefer-standby
