apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-example-13
spec:
  instances: 1
  imageName: quay.io/enterprisedb/postgresql:13.1

  bootstrap:
    initdb:
      database: app

  storage:
    size: 1Gi
  
  walStorage:
    size: 1Gi

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"
