apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-sample
spec:
  instances: 3
  imageName: 'quay.io/enterprisedb/edb-postgres-advanced:15.1'
  licenseKey: '<your_licence_key>'

  postgresql:
    epas:
      tde:
        enabled: true
        secretKeyRef:
          name: tde-key
          key: key
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all

  bootstrap:
    initdb:
      redwood: true

  replicationSlots:
    highAvailability:
      enabled: true
    #updateInterval: 300

  minSyncReplicas: 1
  maxSyncReplicas: 1

  storage:
    size: 1Gi

  walStorage:
    resizeInUseVolumes: true
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"

